name: GitHub Actions Demo

on:
  push:
    branches:
      - main
      - ANewRepo
  workflow_dispatch:
    inputs:
      loglevel:
        type: choice
        options:
          - info
          - warning
          - debug
        default: info
  schedule:
    - cron: '15 6 * * 0'
jobs:
  echo:
    runs-on: github-actions-demo
    steps:
      - name: Run a one-line script
        run: echo "Hello this is a workflow template running log level ${{ github.event.inputs.logLevel }}" 
